final List images = [
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
    "assets/images/profile.png",
  ];
  final List names = [
    "Ram",
    "Shyam",
    "Rahul",
    "Vishal",
    "Sachin",
    "Rahul",
    "Vishal",
    "Sachin",
    "Rahul",
    "Vishal",
  ];
  final List msgTiming = [
    "Today",
    "Yesterday",
    "10:00",
    "15:30",
    "Yesterday",
    "05/02/24",
    "07/02/24",
    "10/02/24",
    "15/03/24",
    "25/02/23",
  ];
  final List msgs = [
    "Hi",
    "Hello",
    "How are you",
    "Good Morning",
    "Good Night",
    "Good Evening",
    "Good Morning",
    "Are u free?",
    "Wanna Play games?",
    "Good Night",
  ];
  final List msgRead = [
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
  ];
